-- Migration: Sync Series & Synopsis
-- Adds support for academic synopses and ghost entries in series.

ALTER TABLE works ADD COLUMN IF NOT EXISTS synopsis TEXT;
ALTER TABLE works ADD COLUMN IF NOT EXISTS in_collection BOOLEAN DEFAULT true;

COMMENT ON COLUMN works.synopsis IS 'Academic, objective summary generated by AI.';
COMMENT ON COLUMN works.in_collection IS 'Whether the physical volume is currently in the collection (false for ghost entries).';
